./start --crawl at
./start --scrape at
./start --crawl au-act
./start --scrape au-act
./start --crawl au-nsw
./start --scrape au-nsw
./start --crawl au-qld
./start --scrape au-qld
./start --crawl au-sa
./start --scrape au-sa
./start --crawl au-tas
./start --scrape au-tas
./start --crawl au-vic
./start --scrape au-vic
./start --crawl au-wa
./start --scrape au-wa
./start --crawl be
./start --scrape be
./start --crawl br
./start --scrape br
